"""work item, clean inbound

Revision ID: 09edf5425ef0
Revises: 2d645f31c116
Create Date: 2026-01-28 16:41:15.446350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09edf5425ef0'
down_revision: Union[str, Sequence[str], None] = '2d645f31c116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inbound_messages_phone_message_uniq'), 'inbound_messages', type_='unique')
    op.drop_index(op.f('ix_inbound_messages_status'), table_name='inbound_messages')
    op.drop_column('inbound_messages', 'last_error')
    op.drop_column('inbound_messages', 'attempts')
    op.drop_column('inbound_messages', 'run_after')
    op.drop_column('inbound_messages', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_messages', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('inbound_messages', sa.Column('run_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('inbound_messages', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inbound_messages', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_inbound_messages_status'), 'inbound_messages', ['status'], unique=False)
    op.create_unique_constraint(op.f('inbound_messages_phone_message_uniq'), 'inbound_messages', ['phone_number_id', 'message_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
