"""tami reminder messages 2

Revision ID: 14ab201ea2ac
Revises: 61639d90cc09
Create Date: 2026-02-04 02:26:55.615521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ab201ea2ac'
down_revision: Union[str, Sequence[str], None] = '61639d90cc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tami_scheduled_messages', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tami_scheduled_messages_sent_at'), 'tami_scheduled_messages', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tami_scheduled_messages_sent_at'), table_name='tami_scheduled_messages')
    op.drop_column('tami_scheduled_messages', 'sent_at')
    # ### end Alembic commands ###
