"""work item

Revision ID: 2d645f31c116
Revises: 697be3229bab
Create Date: 2026-01-28 01:49:03.711735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d645f31c116'
down_revision: Union[str, Sequence[str], None] = '697be3229bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_items',
    sa.Column('work_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('work_id')
    )
    op.create_index(op.f('ix_work_items_business_id'), 'work_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_work_items_client_id'), 'work_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_work_items_created_at'), 'work_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_items_kind'), 'work_items', ['kind'], unique=False)
    op.create_index(op.f('ix_work_items_ref_id'), 'work_items', ['ref_id'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_items_updated_at'), 'work_items', ['updated_at'], unique=False)
    # ### end Alembic commands ###
    op.create_unique_constraint(op.f('inbound_messages_phone_message_uniq'), 'inbound_messages', ['phone_number_id', 'message_id'], postgresql_nulls_not_distinct=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_items_updated_at'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_ref_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_kind'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_created_at'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_client_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_business_id'), table_name='work_items')
    op.drop_table('work_items')
    # ### end Alembic commands ###
