"""baseline

Revision ID: 43c833317072
Revises: 
Create Date: 2026-01-27 23:53:00.000373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c833317072'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('from', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_messages_created_at'), 'inbound_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_inbound_messages_from'), 'inbound_messages', ['from'], unique=False)
    op.create_index(op.f('ix_inbound_messages_message_id'), 'inbound_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_inbound_messages_phone_number_id'), 'inbound_messages', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_inbound_messages_status'), 'inbound_messages', ['status'], unique=False)
    op.create_index(op.f('ix_inbound_messages_timestamp'), 'inbound_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inbound_messages_updated_at'), 'inbound_messages', ['updated_at'], unique=False)
    op.drop_table('outbound_messages')
    op.drop_table('outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('outbox_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('run_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('outbox_id', name=op.f('outbox_pkey'))
    )
    op.create_table('outbound_messages',
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('message_id', name=op.f('outbound_messages_pkey'))
    )
    op.drop_index(op.f('ix_inbound_messages_updated_at'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_timestamp'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_status'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_phone_number_id'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_message_id'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_from'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_created_at'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    # ### end Alembic commands ###
