"""tami reminder messages

Revision ID: 61639d90cc09
Revises: 6d6fd4d35ce6
Create Date: 2026-02-04 01:57:09.097083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61639d90cc09'
down_revision: Union[str, Sequence[str], None] = '6d6fd4d35ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tami_scheduled_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wa_id', sa.String(length=64), nullable=False),
    sa.Column('to_chat_id', sa.String(length=64), nullable=False),
    sa.Column('to_name', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='scheduled', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_id', 'idempotency_key', name='uq_tami_sched_wa_id_idempotency')
    )
    op.create_index('ix_tami_sched_status_send_at', 'tami_scheduled_messages', ['status', 'send_at'], unique=False)
    op.create_index(op.f('ix_tami_scheduled_messages_idempotency_key'), 'tami_scheduled_messages', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_tami_scheduled_messages_send_at'), 'tami_scheduled_messages', ['send_at'], unique=False)
    op.create_index(op.f('ix_tami_scheduled_messages_status'), 'tami_scheduled_messages', ['status'], unique=False)
    op.create_index(op.f('ix_tami_scheduled_messages_to_chat_id'), 'tami_scheduled_messages', ['to_chat_id'], unique=False)
    op.create_index(op.f('ix_tami_scheduled_messages_type'), 'tami_scheduled_messages', ['type'], unique=False)
    op.create_index(op.f('ix_tami_scheduled_messages_wa_id'), 'tami_scheduled_messages', ['wa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tami_scheduled_messages_wa_id'), table_name='tami_scheduled_messages')
    op.drop_index(op.f('ix_tami_scheduled_messages_type'), table_name='tami_scheduled_messages')
    op.drop_index(op.f('ix_tami_scheduled_messages_to_chat_id'), table_name='tami_scheduled_messages')
    op.drop_index(op.f('ix_tami_scheduled_messages_status'), table_name='tami_scheduled_messages')
    op.drop_index(op.f('ix_tami_scheduled_messages_send_at'), table_name='tami_scheduled_messages')
    op.drop_index(op.f('ix_tami_scheduled_messages_idempotency_key'), table_name='tami_scheduled_messages')
    op.drop_index('ix_tami_sched_status_send_at', table_name='tami_scheduled_messages')
    op.drop_table('tami_scheduled_messages')
    # ### end Alembic commands ###
