"""work item

Revision ID: 697be3229bab
Revises: 43c833317072
Create Date: 2026-01-28 01:44:57.631878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697be3229bab'
down_revision: Union[str, Sequence[str], None] = '43c833317072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inbound_messages_phone_message_uniq'), 'inbound_messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('inbound_messages_phone_message_uniq'), 'inbound_messages', ['phone_number_id', 'message_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
