"""events client, provider

Revision ID: 6d6fd4d35ce6
Revises: 8df46c74ec8a
Create Date: 2026-02-04 00:27:49.728142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6fd4d35ce6'
down_revision: Union[str, Sequence[str], None] = '8df46c74ec8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_items', sa.Column('client_id', sa.String(length=64), nullable=False))
    op.add_column('event_items', sa.Column('provider_id', sa.String(length=64), nullable=False))
    op.add_column('event_items', sa.Column('service_id', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_event_items_user_id'), table_name='event_items')
    op.drop_index(op.f('ux_event_items_user_gcal_event_id'), table_name='event_items', postgresql_where='(gcal_event_id IS NOT NULL)')
    op.drop_index(op.f('ux_event_items_user_op_id'), table_name='event_items', postgresql_where='(op_id IS NOT NULL)')
    op.create_index('ux_event_items_user_op_id', 'event_items', ['provider_id', 'client_id', 'op_id'], unique=True, postgresql_where=sa.text('op_id IS NOT NULL'))
    op.create_index(op.f('ix_event_items_client_id'), 'event_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_event_items_provider_id'), 'event_items', ['provider_id'], unique=False)
    op.create_index(op.f('ix_event_items_service_id'), 'event_items', ['service_id'], unique=False)
    op.create_index('ux_event_items_provider_gcal_event_id', 'event_items', ['provider_id', 'gcal_event_id'], unique=True, postgresql_where=sa.text('gcal_event_id IS NOT NULL'))
    op.drop_column('event_items', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_items', sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index('ux_event_items_provider_gcal_event_id', table_name='event_items', postgresql_where=sa.text('gcal_event_id IS NOT NULL'))
    op.drop_index(op.f('ix_event_items_service_id'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_provider_id'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_client_id'), table_name='event_items')
    op.drop_index('ux_event_items_user_op_id', table_name='event_items', postgresql_where=sa.text('op_id IS NOT NULL'))
    op.create_index(op.f('ux_event_items_user_op_id'), 'event_items', ['user_id', 'op_id'], unique=True, postgresql_where='(op_id IS NOT NULL)')
    op.create_index(op.f('ux_event_items_user_gcal_event_id'), 'event_items', ['user_id', 'gcal_event_id'], unique=True, postgresql_where='(gcal_event_id IS NOT NULL)')
    op.create_index(op.f('ix_event_items_user_id'), 'event_items', ['user_id'], unique=False)
    op.drop_column('event_items', 'service_id')
    op.drop_column('event_items', 'provider_id')
    op.drop_column('event_items', 'client_id')
    # ### end Alembic commands ###
