"""temporal 

Revision ID: 7aff5bbf3213
Revises: ac4eed37c643
Create Date: 2026-02-13 04:07:59.596673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7aff5bbf3213'
down_revision: Union[str, Sequence[str], None] = 'ac4eed37c643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Jerusalem', nullable=False),
    sa.Column('google_calendar_id', sa.String(length=256), server_default='primary', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_business_provider_user_id')
    )
    op.create_index('business_providers_business_id_idx', 'business_providers', ['business_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_clients_user_id')
    )
    op.create_index('clients_business_id_idx', 'clients', ['business_id'], unique=False)
    op.create_table('user_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('is_provider', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_routes_user_id')
    )
    op.create_index('user_routes_business_id_idx', 'user_routes', ['business_id'], unique=False)
    op.drop_index(op.f('ix_work_items_business_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_client_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_created_at'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_kind'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_ref_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_updated_at'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_table('users')
    op.drop_index(op.f('businesses_wa_id_idx'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_wa_id'), table_name='businesses')
    op.drop_column('businesses', 'providers_json')
    op.drop_column('businesses', 'wa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('wa_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('businesses', sa.Column('providers_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_businesses_wa_id'), 'businesses', ['wa_id'], unique=False)
    op.create_index(op.f('businesses_wa_id_idx'), 'businesses', ['wa_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_table('work_items',
    sa.Column('work_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ref_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('run_after', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('work_id', name=op.f('work_items_pkey'))
    )
    op.create_index(op.f('ix_work_items_updated_at'), 'work_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_items_ref_id'), 'work_items', ['ref_id'], unique=False)
    op.create_index(op.f('ix_work_items_kind'), 'work_items', ['kind'], unique=False)
    op.create_index(op.f('ix_work_items_created_at'), 'work_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_items_client_id'), 'work_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_work_items_business_id'), 'work_items', ['business_id'], unique=False)
    op.drop_index('user_routes_business_id_idx', table_name='user_routes')
    op.drop_table('user_routes')
    op.drop_index('clients_business_id_idx', table_name='clients')
    op.drop_table('clients')
    op.drop_index('business_providers_business_id_idx', table_name='business_providers')
    op.drop_table('business_providers')
    # ### end Alembic commands ###
