"""events

Revision ID: 8df46c74ec8a
Revises: 68428506770a
Create Date: 2026-02-03 02:03:10.504048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8df46c74ec8a'
down_revision: Union[str, Sequence[str], None] = '68428506770a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('op_id', sa.String(length=128), nullable=True),
    sa.Column('item_type', sa.String(length=32), server_default='event', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('gcal_event_id', sa.String(length=256), nullable=True),
    sa.Column('allow_conflicts', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recurrence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reminders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delete_scope', sa.String(length=32), server_default='single', nullable=False),
    sa.Column('send_updates', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notify', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("delete_scope IN ('single','series','this_and_following')", name='ck_event_items_delete_scope'),
    sa.CheckConstraint("item_type = 'event'", name='ck_event_items_item_type'),
    sa.CheckConstraint("status IN ('open','completed','deleted')", name='ck_event_items_status'),
    sa.CheckConstraint('\n            (\n              all_day = true\n              AND date IS NOT NULL\n              AND end_date IS NOT NULL\n              AND start_at IS NULL\n              AND end_at IS NULL\n            )\n            OR\n            (\n              all_day = false\n              AND start_at IS NOT NULL\n              AND end_at IS NOT NULL\n              AND date IS NULL\n              AND end_date IS NULL\n            )\n            ', name='ck_event_items_time_shape'),
    sa.CheckConstraint('\n            (all_day = true AND end_date > date)\n            OR\n            (all_day = false AND end_at > start_at)\n            ', name='ck_event_items_end_after_start'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_items_all_day'), 'event_items', ['all_day'], unique=False)
    op.create_index(op.f('ix_event_items_created_at'), 'event_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_items_date'), 'event_items', ['date'], unique=False)
    op.create_index(op.f('ix_event_items_delete_scope'), 'event_items', ['delete_scope'], unique=False)
    op.create_index(op.f('ix_event_items_end_at'), 'event_items', ['end_at'], unique=False)
    op.create_index(op.f('ix_event_items_end_date'), 'event_items', ['end_date'], unique=False)
    op.create_index(op.f('ix_event_items_gcal_event_id'), 'event_items', ['gcal_event_id'], unique=False)
    op.create_index(op.f('ix_event_items_item_type'), 'event_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_event_items_op_id'), 'event_items', ['op_id'], unique=False)
    op.create_index(op.f('ix_event_items_start_at'), 'event_items', ['start_at'], unique=False)
    op.create_index(op.f('ix_event_items_status'), 'event_items', ['status'], unique=False)
    op.create_index(op.f('ix_event_items_updated_at'), 'event_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_event_items_user_id'), 'event_items', ['user_id'], unique=False)
    op.create_index('ux_event_items_user_gcal_event_id', 'event_items', ['user_id', 'gcal_event_id'], unique=True, postgresql_where=sa.text('gcal_event_id IS NOT NULL'))
    op.create_index('ux_event_items_user_op_id', 'event_items', ['user_id', 'op_id'], unique=True, postgresql_where=sa.text('op_id IS NOT NULL'))
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.drop_index('ux_event_items_user_op_id', table_name='event_items', postgresql_where=sa.text('op_id IS NOT NULL'))
    op.drop_index('ux_event_items_user_gcal_event_id', table_name='event_items', postgresql_where=sa.text('gcal_event_id IS NOT NULL'))
    op.drop_index(op.f('ix_event_items_user_id'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_updated_at'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_status'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_start_at'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_op_id'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_item_type'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_gcal_event_id'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_end_date'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_end_at'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_delete_scope'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_date'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_created_at'), table_name='event_items')
    op.drop_index(op.f('ix_event_items_all_day'), table_name='event_items')
    op.drop_table('event_items')
    # ### end Alembic commands ###
