"""inbound dedup

Revision ID: ac4eed37c643
Revises: 14ab201ea2ac
Create Date: 2026-02-08 03:00:50.927971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4eed37c643'
down_revision: Union[str, Sequence[str], None] = '14ab201ea2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inbound_phone_message', 'inbound_messages', ['phone_number_id', 'message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inbound_phone_message', 'inbound_messages', type_='unique')
    # ### end Alembic commands ###
