"""business model, reducer 1

Revision ID: ce8b1bdde59b
Revises: 09edf5425ef0
Create Date: 2026-01-28 22:20:42.302090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce8b1bdde59b'
down_revision: Union[str, Sequence[str], None] = '09edf5425ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('wa_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Jerusalem', nullable=False),
    sa.Column('booking_policy_mode', sa.String(length=32), server_default='owner_confirm', nullable=False),
    sa.Column('enable_digest', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('booking_policy_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('reminder_policy_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('working_hours_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('services_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('providers_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('businesses_booking_policy_mode_idx', 'businesses', ['booking_policy_mode'], unique=False)
    op.create_index('businesses_wa_id_idx', 'businesses', ['wa_id'], unique=False)
    op.create_index(op.f('ix_businesses_business_id'), 'businesses', ['business_id'], unique=True)
    op.create_index(op.f('ix_businesses_wa_id'), 'businesses', ['wa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_wa_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_id'), table_name='businesses')
    op.drop_index('businesses_wa_id_idx', table_name='businesses')
    op.drop_index('businesses_booking_policy_mode_idx', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
