"""scheduled massage

Revision ID: faeb12efc4d8
Revises: ce8b1bdde59b
Create Date: 2026-01-29 01:28:40.751612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faeb12efc4d8'
down_revision: Union[str, Sequence[str], None] = 'ce8b1bdde59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_scheduled_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.Text(), nullable=False),
    sa.Column('wa_id', sa.String(length=64), nullable=False),
    sa.Column('to_chat_id', sa.String(length=64), nullable=False),
    sa.Column('to_name', sa.Text(), nullable=True),
    sa.Column('interactive_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='scheduled', nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_scheduled_messages_business_id'), 'business_scheduled_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_scheduled_messages_idempotency_key'), 'business_scheduled_messages', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_business_scheduled_messages_send_at'), 'business_scheduled_messages', ['send_at'], unique=False)
    op.create_index(op.f('ix_business_scheduled_messages_status'), 'business_scheduled_messages', ['status'], unique=False)
    op.create_index(op.f('ix_business_scheduled_messages_to_chat_id'), 'business_scheduled_messages', ['to_chat_id'], unique=False)
    op.create_index(op.f('ix_business_scheduled_messages_wa_id'), 'business_scheduled_messages', ['wa_id'], unique=False)
    op.create_index(op.f('ix_business_scheduled_messages_workflow_id'), 'business_scheduled_messages', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_scheduled_messages_workflow_id'), table_name='business_scheduled_messages')
    op.drop_index(op.f('ix_business_scheduled_messages_wa_id'), table_name='business_scheduled_messages')
    op.drop_index(op.f('ix_business_scheduled_messages_to_chat_id'), table_name='business_scheduled_messages')
    op.drop_index(op.f('ix_business_scheduled_messages_status'), table_name='business_scheduled_messages')
    op.drop_index(op.f('ix_business_scheduled_messages_send_at'), table_name='business_scheduled_messages')
    op.drop_index(op.f('ix_business_scheduled_messages_idempotency_key'), table_name='business_scheduled_messages')
    op.drop_index(op.f('ix_business_scheduled_messages_business_id'), table_name='business_scheduled_messages')
    op.drop_table('business_scheduled_messages')
    # ### end Alembic commands ###
