"""add event_log

Revision ID: 329a1484cf88
Revises: f0d514b371f2
Create Date: 2026-01-27 03:31:33.086037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '329a1484cf88'
down_revision: Union[str, Sequence[str], None] = 'f0d514b371f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from alembic import op
    import sqlalchemy as sa

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('outbox_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
    op.create_index("ix_event_log_outbox_ts", "event_log", ["outbox_id", "ts"])
    op.create_index("ix_event_log_biz_client_ts", "event_log", ["business_id", "client_id", "ts"])
    op.create_index("ix_event_log_event_ts", "event_log", ["event", "ts"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_log')
    # ### end Alembic commands ###
